### ISSUE TITLE
issue with .stversions

### ISSUE THREAD

**Issue by malvism** [didi1357/SyncMessCleaner#1]
I had a mess with Syncthing, so it made a few hundreds of conflict files. In the beginning I deleted them on my WinPC, so on my *nix box they were put in .stversions folder. As the files were quite a lot, I found your nice script to run on *nix box - thanks for it @didi1357  :) 

But I ran in the issue that scripts finds a .sync-conflict file in .stversions, then tries to crc hash, but fails, because the file without sync-conflict doesn't exist.

`Traceback (most recent call last):
  File "SyncMessCleaner-readonly.py", line 65, in <module>
    main(sys.argv[1])
  File "SyncMessCleaner-readonly.py", line 50, in main
    original_crc = crc(os.path.join(directory, original_name))
  File "SyncMessCleaner-readonly.py", line 8, in crc
    for eachLine in open(file, "rb"):
FileNotFoundError: [Errno 2] No such file or directory: '/home/st/sync/u_m/.stversions/_fotovideo/DSC_0851.JPG'`

Unfortunately the script terminates and does not skip-over the issue.
So it should check if file without ".sync-conflict" really exists, or at least just skip it (but not terminate script).

**Comment by didi1357** [comment]
I think I'll add a check for the .stversion folder... In my opinion a missing second file should stay something which leads to abortion and report to the user, as this normally won't happen. :)

But nice to hear that it was useful for someone else :)

**Comment by didi1357** [comment]
Fixed in 74b6673

**Comment by malvism** [comment]
I made it like this
`original_name = base_name + extension

            if os.path.isfile(os.path.join(directory, original_name)): # ADDED
                conflict_crc = crc(os.path.join(directory, conflict_file_name))
                original_crc = crc(os.path.join(directory, original_name))

                if original_crc == conflict_crc:
                    #os.unlink(os.path.join(directory, conflict_file_name))
                    print("Deleted " + conflict_file_name + " as it has the same CRC as the original file.")
                else:
                    print("Warning: There are real differences between " + original_name +  " and the conflicting file in " + directory)
            else: # ADDED
                print("Warning: there is no original file " + original_name + " in the directory " + directory) # ADDED`

Because there might be a situation (outside .stversions) when I deleted the original file (as it's really different from conflict), but haven't renamed the file to exclude sync conflict, so it terminates the script with error... 

And there is no need to keed duplicates in  .stversions if they are the same files :)

**Comment by didi1357** [comment]
> And there is no need to keed duplicates in .stversions if they are the same files :)

True. I should have slept over your suggestions in the first place, before implementing the small change that fast...

I also thought again about your situation and why a selfmade warning could be better than the python error. The main benefit is that the script goes on with the other files without stopping, right? :)

I'll again add your changes to master branch :) thx :)

**Comment by didi1357** [comment]
Fixed in 766addc

**Comment by malvism** [comment]
> The main benefit is that the script goes on with the other files without stopping, right? :)

Yes, especially taking into account that crc checking takes quite a lot of time and I just left the script running for half day (I had a mess of ~100GB)... It's nicer to have just warning message about that, not script being stopped with fatal error :)


> I'll again add your changes to master branch :) thx :)

I'm happy that my code was so useful :) (taking into account I'm not programmer and first time with python I spent half an hour trying to resolve error which was caused by tabs and spaces...)

**Comment by didi1357** [comment]
> (taking into account I'm not programmer and first time with python I spent half an hour trying to resolve error which was caused by tabs and spaces...)

If you've got the time read through PEP-8... Otherwise just use Pycharm. The community version is free right now :) It provides a lot of hinting and autoformatting.
