### ISSUE TITLE
Fails on actual conflicts

### ISSUE THREAD

**Issue by muejam09** [didi1357/SyncMessCleaner#2]
The script errors if there are actual conflicts with the following error message:
...`
Finished building ToDo list. Will begin with checking:
Traceback (most recent call last):
  File "SyncMessCleaner.py", line 68, in <module>
    main(sys.argv[1])
  File "SyncMessCleaner.py", line 48, in main
    if os.path.isfile(os.path.join(directory, original_name)):
UnboundLocalError: local variable 'original_name' referenced before assignment`

**Comment by didi1357** [comment]
Damn.. Looks like i put the if one line too early.. Sry.. Will fix ASAP..

**Comment by didi1357** [comment]
Done
